### ISSUE TITLE
Where to find your public key?

### ISSUE THREAD

**Issue by mikhailian** [nadiaholmquist/pbp-packages#7]
`pacman-key --recv-keys 50626D06C63A8C774FCB35D2497FE64338F993E9` does not seem to work anymore, as SKS is kind of down, I searched on keyserver.ubuntu.com and your key is not found there.

**Comment by nadiaholmquist** [comment]
https://keys.openpgp.org/vks/v1/by-fingerprint/50626D06C63A8C774FCB35D2497FE64338F993E9

**Comment by mikhailian** [comment]
Thanks.

I see that `pacman-key --recv-keys 50626D06C63A8C774FCB35D2497FE64338F993E9` works again now.
